### ISSUE TITLE
Generating Q# from JS/TypeScript

### ISSUE THREAD

**Issue by mapmeld** [ebraminio/awesome-qsharp#10]
Hi Q# community,

I have a JavaScript module [QuantumPeep](https://quantumpeep.com) which allows you to create gate code and export to Q# (and other quantum languages)

I was going to do a PR adding a link to the code https://github.com/mapmeld/quantum-peep but I don't know where you think it might go categorywise... maybe other Demos and Samples? Let me know if it might be a fit

**Comment by ebraminio** [comment]
Wow, this is so awesome, maybe adding a See Also section or whatever you see fit best. Thank you so much!
